### ISSUE TITLE
Incorrect de-escaping on creating post or updating them

### ISSUE THREAD

**Issue by BrunoWinck** [WP-API/WP-API#1643]
When I modifiy a post like this

```
Service.UpdatePost( 6290, "test", '[shortcode val="jj"]<img src="aa0.png" />[/shortcode]', "tags;tags1", "", "", "");
```

I end up with this in the database

```
[shortcode val=\"jj\"]<img src=\"aa00.png\" />[/shortcode]
```

Yes \" are not wanted :) It's totally wrong, unusable and even dangerous because it can destroy a complete blog.

Don't wonder about my code and the stack on my side, let's jump directly to the HTTP Request I captured.

```
C:\Project\kneaver\Kneaver\KNVStreams\ScriptDemo>curl --verbose --request POST 'http://localhost:92/wp-json/wp/v2/posts' --user-ag
ent 'curl/7.15.5 (i386-redhat-linux-gnu) libcurl/7.15.5 OpenSSL/0.9.8b zlib/1.2.3 libidn/0.6.5'--header 'Authorization: ffff\r\nContent-Type: application/x-www-form-urlencoded\r\n'--data 'tit
le=test&content=ok%20this%20is%20interesting%2c%20lets%20try%20some%20Chinese%20%e6%b2%bf%e5%af%b9%e8%af%9d'
```

let's percent decode the data using http://meyerweb.com/eric/tools/dencoder/

```
title=test&content=[shortcode val="jj"]<img src="aa00.png" />[/shortcode]
```

As you can see my data was not protected and perfectly proper

I tried to search in the code what could be wrong. 

I went down to 
```
$prepared_post->post_content = wp_filter_post_kses( $request['content'] );
```
traces:
```
before:[shortcode val=\"jj\"]ok this is interesting, lets try some Chinese 沿对话<img src=\"aa0.png\" />[/shortcode]
after:[shortcode val=\"jj\"]ok this is interesting, lets try some Chinese 沿对话<img src=\"aa00.png\" />[/shortcode]
```

so data is damaged already before

`wp_filter_post_kses` will only deals with HTML tags (so not concerned by json like escaping)

before that when building the request there is a mechanism mixing santizing and defaulting to `sanitize_callback`. I've not been able to figure out where this escaping would be done.

At this stage it came to my mind that it could be related to using classical url-encoding for post data instead of json. Someone may have escaped it to align with json and forgot to unescape it?

NB: Chinese was properly transferred from url-encoded tf8 to plain utf8.
NB2: Markdown is cleaning the bug in the img tah so it appears ok, it's wrong really.

**Comment by rmccue** [comment]
Seems like we're maybe not unslashing the input correctly.

**Comment by BrunoWinck** [comment]
The input don't contain backslashes. This works well on xmlrpc.
Now it may happen that it contains backslashes for other purposes, \ is allowed in HTML5.
I learned from the migration to UTF8 that keeping encoding and decoding stuff that didn't require encoding can lead to lots of confusion. IMHO Json only should be unslahed in the request structure and form url-encoded left unchanged.

Same for use of sanitize Although In understand the desire to protect comments I'm a bit concerned by protecting what an author may publish in a post. I typically add a lot of html: iframe, svg, javascript, css. 

thanks for adding the code marks for markdown :)

**Comment by danwatt** [comment]
What version of PHP are you running? I had a similar bug (#1469), and it was fixed by upgrading from PHP 5.4 to 5.6.

**Comment by BrunoWinck** [comment]
Good point! I have 5.4.9 
I suspected it could be that days after but WP don't ask 5.6, no complain, no error.
If this was true the plugins should not allow 5.4.9, so bug remains open.
Meanwhile I returned to xlmrpc, will wait for more mature versions

**Comment by danielbachhuber** [comment]
This was fixed in beta8 / #1772
